# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Plan Your Recovery
email: npresnall@planyourrecovery.com
description: >
  A place for answers about addiction and recovery.
logo: "/assets/images/pyr-logo.svg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://planyourrecovery.com" # the base hostname & protocol for your site
paginate:	8 # The number of posts to show per page on your homepage
excerpt_separator: <!--more-->

name: 'Ned Presnall'
bio: >
  Ned is Executive Director of Clayton Behavioral and Adjunct Professor at Washington University in St. Louis, Missouri. 
  He presents widely on the topics of addiction, mental health, and Medication Assisted Treatment. 
  Ned is passionate about reducing the stigma against persons with addiction and against Medication Assisted Treatment through discourse and public engagement.
  
author_image: "assets/images/ned_presnall.jpg"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed

